# Generated by Django 3.1.7 on 2021-04-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='postFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(default='', max_length=250)),
                ('campuslocation', models.CharField(max_length=250)),
                ('typefood', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
