# Generated by Django 3.1.7 on 2021-04-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccapp', '0003_employeetable_studenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='postEvent1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(default='', max_length=250)),
                ('campuslocation', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('universityname', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='postFood1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organizationname', models.CharField(default='', max_length=250)),
                ('campuslocation', models.CharField(max_length=250)),
                ('typefood', models.CharField(max_length=250)),
                ('capacity', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('universityname', models.CharField(max_length=250)),
            ],
        ),
    ]
